version: '3'

services:
  fastapi:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 8000:8000
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge